import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-center w-screen h-screen overflow-hidden select-none">
          <div className="flex justify-center w-[393px] bg-main-bg overflow-hidden">
            <Header />
            {children}
            <Footer />
          </div>
        </div>
        <div id="portal-root" />
      </body>
    </html>
  );
}
